# Generated by Django 5.1.4 on 2024-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stockdata_remove_jobapplication_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Growth', 'Growth Portfolio'), ('Income', 'Income Portfolio'), ('Balanced', 'Balanced Portfolio'), ('Aggressive', 'Aggressive Portfolio'), ('Conservative', 'Conservative Portfolio')], max_length=100)),
                ('ticker', models.CharField(choices=[('RELIANCE.BO', 'Reliance Industries'), ('TCS.BO', 'Tata Consultancy Services'), ('INFY.BO', 'Infosys Limited'), ('HDFCBANK.BO', 'HDFC Bank'), ('ICICIBANK.BO', 'ICICI Bank'), ('ITC.BO', 'ITC Limited'), ('LT.BO', 'Larsen & Toubro'), ('SBIN.BO', 'State Bank of India'), ('HINDUNILVR.BO', 'Hindustan Unilever'), ('BAJAJFIN.BO', 'Bajaj Finance')], max_length=15)),
                ('company_name', models.CharField(choices=[('RELIANCE.BO', 'Reliance Industries'), ('TCS.BO', 'Tata Consultancy Services'), ('INFY.BO', 'Infosys Limited'), ('HDFCBANK.BO', 'HDFC Bank'), ('ICICIBANK.BO', 'ICICI Bank'), ('ITC.BO', 'ITC Limited'), ('LT.BO', 'Larsen & Toubro'), ('SBIN.BO', 'State Bank of India'), ('HINDUNILVR.BO', 'Hindustan Unilever'), ('BAJAJFIN.BO', 'Bajaj Finance')], max_length=100)),
                ('shares', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
